pipeline {
  agent any
  environment {
    PYTHONUNBUFFERED = 'TRUE'
  }
  stages {
    stage('Build and Install') {
      steps {
        sh '''pip3 install --upgrade --force-reinstall . "awscli>1.20.30" "sagemaker" "boto3"'''
      }
    }
    stage('Update and Run Deploy Script') {
      steps {
        withAWS(credentials:"${AWS_CREDENTIAL}") {
          sh '''
          cd deploy
          python deploy.py --config_file ${CONFIG_FILE_NAME}
          echo "Deploy completed."
        }
      }
    }
  }
}
