pipeline {
  agent any
  environment {
    PYTHONUNBUFFERED = 'TRUE'
  }
  stages {
    stage('Build and Install') {
      steps {
        sh '''pip3 install "awscli" "sagemaker" "boto3"'''
      }
    }
    stage('Update and Run Deploy Script') {
      steps {
        withAWS(credentials:"${AWS_CREDENTIAL}") {
          sh '''
          export AWS_DEFAULT_REGION=${AWS_REGION}
          cd deploy
          python3 deploy.py --config_file ${CONFIG_FILE_NAME}
          echo "Deploy completed."
          '''
        }
      }
    }
  }
}
